language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
  - pip install -e .
  - pip install -r requirements/tests.txt
  - pip install coveralls
script: py.test --cov-report=term-missing
after_success: coveralls
